### ISSUE TITLE
Couldn't find downloaded files 

### ISSUE THREAD

**Issue by traviss64** [vegidio/reddit-media-downloader#1]
First time focker user & this was so confusing. Somehow managed to made it worked but couldn't find the files. WSL which is installed doesn't let users to access MNT folder and during docker environment filling can't set the location. When I tried putting the code you mentioned in terminal in the docker it was giving loads of error from using $ to wrong "docker" name.

Can you PLEASE put put a user friendly guide?

Edit: Okay, I found it. Under the docker itself there is FILES option and there were the downloaded files.

**Comment by vegidio** [comment]
Firstly, I never intended that the instructions on how to use this media downloader would also cover how to use Docker. If you never used Docker before then I'm sure you can find numerous tutorials online about that. Also, the fact that apparently you're trying to run the command with `$` tells that you should familiarize yourself with the command prompt.

After you get these two requirements out of the way then you will realize that the instructions are already user friendly.
